### ISSUE TITLE
Getting delete to work properly

### ISSUE THREAD

**Issue by Decade** [AlgorithmsMeetup/Autocomplete#1]
The issue with the delete method in the presented solution is that any trie does not know the prefix that led to it, and also cannot delete itself, and also empty string is falsy. Here’s a solution that I imagine would work correctly:

1) Check whether there is a matching child node (you may be asked to remove a word that is not in the trie).
2) Recurse into the child node, telling it to delete the suffix (or just delete the end of word marker, if it’s at the end of the word).
3) Check whether the child has any children anymore (either end of word or 1 or more suffixes).
4) If not, then it’s safe to delete that child.

**Comment by Syeoryn** [comment]
Thanks!  That's pretty close to the solution I came up with for that problem.  I added tests for this in the latest commit on master (a5987b), and that solution was added in the solution brach with commit 826b07.
